### ISSUE TITLE
Cannot find module 'sha256'

### ISSUE THREAD

**Issue by IsaacHuang** [sDAGraph/sDAG-SDK-js#1]
When I install this and run const sdag = require("sdagraph"), show up the following message, Error: Cannot find module 'sha256'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/is*********g/node_modules/sdagraph/src/account.js:2:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by TXien** [comment]
npm install sha256
